---
title: CodeBook.md
author: Mark Harnett
date: December 27, 2015
output: html_document
---

The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. These time domain signals (prefix 't' to denote time) were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (tBodyAcc-XYZ and tGravityAcc-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz.

Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag).

Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag. (Note the 'f' to indicate frequency domain signals).

These signals were used to estimate variables of the feature vector for each pattern:
'-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.

subject: the number/ID used to indicate individual subjects 
activity: the activity being monitored. 
body_acc_x_mean: the mean of all the estimated Triaxial body acceleration points recorded in X dimension 


body_acc_x_sd: the standard deviation of all the estimated Triaxial body acceleration points recorded in X dimension 
body_acc_y_mean: the mean of all the estimated Triaxial body acceleration points recorded in Y dimension 
body_acc_y_sd: the standard deviation of all the estimated Triaxial body acceleration points recorded in Y dimension 
body_acc_z_mean: the mean of all the estimated Triaxial body acceleration points recorded in Z dimension 
body_acc_z_sd: the standard deviation of all the estimated Triaxial body acceleration points recorded in Z dimension 
body_gyro_x_mean: the mean of all Triaxial Angular velocity from the gyroscope data points recorded in X dimension 
body_gyro_x_sd: the standard deviation of all Triaxial Angular velocity from the gyroscope data points recorded in X dimension 
body_gyro_y_mean: the mean of all Triaxial Angular velocity from the gyroscope data points recorded in Y dimension 
body_gyro_y_sd: the standard deviation of all Triaxial Angular velocity from the gyroscope data points recorded in Y dimension 
body_gyro_z_mean: the mean of all Triaxial Angular velocity from the gyroscope data points recorded in Z dimension 
body_gyro_z_sd: the standard deviation of all Triaxial Angular velocity from the gyroscope data points recorded in Z dimension 
total_acc_x_mean: the mean of all Triaxial acceleration from the accelerometer data points recorded in X dimension 
total_acc_x_sd: the standard deviation of all Triaxial acceleration from the accelerometer data points recorded in X dimension 
total_acc_y_mean: the mean of all Triaxial acceleration from the accelerometer data points recorded in Y dimension 
total_acc_y_sd: the standard deviation of all Triaxial acceleration from the accelerometer data points recorded in Y dimension 
total_acc_z_mean: the mean of all Triaxial acceleration from the accelerometer data points recorded in Z dimension 
total_acc_z_sd: the standard deviation of all Triaxial acceleration from the accelerometer data points recorded in Z dimension 
dataType: indicating if the data set is from test or train data